services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  keron_digital.redis_storage.blacklist:
    class: KeronDigital\AuthRedisStorageBundle\Infrastructure\Persistence\RedisTokenBlacklist
    arguments:
      $keyPrefix: '%keron_digital.redis_storage.blacklist.prefix%'

  KeronDigital\AuthRedisStorageBundle\Domain\Contract\TokenBlacklistInterface:
    alias: keron_digital.redis_storage.blacklist
    public: true

  keron_digital.redis_storage.active_token_storage:
    class: KeronDigital\AuthRedisStorageBundle\Infrastructure\Persistence\RedisActiveTokenStorage
    arguments:
      $keyPrefix: '%keron_digital.redis_storage.active_storage.prefix%'

  KeronDigital\AuthRedisStorageBundle\Domain\Contract\ActiveTokenStorageInterface:
    alias: keron_digital.redis_storage.active_token_storage
    public: true
    